## Handling Missing Values

In [12]:
from sklearn.impute import SimpleImputer
import numpy as np
import pandas as pd

In [4]:
#create data
#the default value for a missing feature entry is NaN
data = np.array([[1,np.nan,2],[2,3,np.nan],[-1,4,2]])

data

array([[ 1., nan,  2.],
       [ 2.,  3., nan],
       [-1.,  4.,  2.]])

In [9]:
# Create an instance of SimpleImputer
imputer = SimpleImputer(strategy='mean')

# Fit and transform the data using the imputer
data_imputed = imputer.fit_transform(data)

print(data_imputed)

[[ 1.   3.5  2. ]
 [ 2.   3.   2. ]
 [-1.   4.   2. ]]


In [10]:
# Create an instance of SimpleImputer
imputer = SimpleImputer(strategy='median')

# Fit and transform the data using the imputer
data_imputed = imputer.fit_transform(data)


print(data_imputed)

[[ 1.   3.5  2. ]
 [ 2.   3.   2. ]
 [-1.   4.   2. ]]


In [11]:
# Create an instance of SimpleImputer
imputer = SimpleImputer(strategy='most_frequent')

# Fit and transform the data using the imputer
data_imputed = imputer.fit_transform(data)


print(data_imputed)

[[ 1.  3.  2.]
 [ 2.  3.  2.]
 [-1.  4.  2.]]


### Dictionary of Lists

In [13]:
dict = {'First Score':[100,90,np.nan,95],
       'Second Score':[30,45,56,np.nan],
       'Third Score':[np.nan,40,80,98]}

#creating a dataframe from list 
df = pd.DataFrame(dict)

#using isnull() function
df.isnull()

First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [14]:
#filling missing values using fillna()
df.fillna(0)

First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [15]:
#filling null values using fillna() function 
#code 3: Filling null value with the next ones
df.fillna(method='bfill')

First Score  Second Score  Third Score
0        100.0          30.0         40.0
1         90.0          45.0         40.0
2         95.0          56.0         80.0
3         95.0           NaN         98.0