In [2]:
l = [1,2,3]
l

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(1)

array(1)

In [5]:
np.empty(2)

array([-2.26825602e+200,  2.94875483e+233])

#### With caution

In [6]:
np.empty(100)

array([0.00000000e+000, 6.95243190e-310, 3.68078906e-321,             nan,
       1.05344234e-311, 0.00000000e+000, 3.77704695e+233, 7.22756687e+159,
       1.10639950e+200, 3.64726544e+180, 1.87750993e-152, 4.82336277e+228,
       9.23528171e+242, 2.52960802e-258, 4.47593816e-091, 1.76353931e-070,
       8.63819469e-096, 7.12930810e+159, 2.61191759e+209, 2.25020976e+223,
       1.67640691e+243, 1.24595996e-089, 1.74593501e+238, 1.13556093e-153,
       1.96088695e+243, 9.82391603e+252, 3.62479391e+228, 1.32655511e-258,
       7.22082943e+159, 6.03433819e-154, 2.35570319e+251, 4.77800043e+180,
       5.80426330e+180, 2.19980343e-152, 1.12038868e+219, 2.31881454e-152,
       6.01346953e-154, 5.82147482e+180, 6.12486739e+257, 4.47593784e-091,
       1.45291304e-094, 1.62596915e-086, 1.43615024e+161, 6.01334682e-154,
       2.59345433e+161, 6.72801012e+199, 9.13601355e+242, 1.48504071e+161,
       1.45913393e-152, 1.12044105e+219, 2.63422477e-085, 3.88281160e+233,
       1.27966001e-152, 1

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### A Ranage -arange

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
l = [4,32,14,21,4,65,4,17]
l

[4, 32, 14, 21, 4, 65, 4, 17]

In [18]:
ar = np.array(l)

In [19]:
ar

array([ 4, 32, 14, 21,  4, 65,  4, 17])

In [20]:
ar.max()

65

In [21]:
ar.argmax() #65 

5

In [22]:
ar.argmin()

0

In [23]:
ar.shape #8elements

(8,)

In [24]:
len(ar.tolist())

8

In [26]:
np.ones(10, np.int16)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [27]:
ar.dtype

dtype('int32')