In [1]:
import numpy as np

In [2]:
a1 = np.arange(0,20,2).reshape(2,5)
a1

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [4]:
a2 = np.arange(1,20,2).reshape(2,5)
a2

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [5]:
a1 + a2

array([[ 2,  6, 10, 14, 18],
       [22, 26, 30, 34, 38]])

#### Mathematical Functions 

In [6]:
np.add(a1,a2) #add

array([[ 2,  6, 10, 14, 18],
       [22, 26, 30, 34, 38]])

In [7]:
np.mod(a1,3) #mod

array([[1, 0, 2, 1, 0],
       [2, 1, 0, 2, 1]], dtype=int32)

In [9]:
np.power(a1,3) #power

array([[   1,   27,  125,  343,  729],
       [1331, 2197, 3375, 4913, 6859]], dtype=int32)

In [10]:
np.sqrt(a1) #sqrt

array([[1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ],
       [3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894]])

#### Trigonometric functions

In [11]:
np.sin(a1) #sin

array([[ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849],
       [-0.99999021,  0.42016704,  0.65028784, -0.96139749,  0.14987721]])

In [12]:
np.tan(a1) #tan

array([[ 1.55740772e+00, -1.42546543e-01, -3.38051501e+00,
         8.71447983e-01, -4.52315659e-01],
       [-2.25950846e+02,  4.63021133e-01, -8.55993401e-01,
         3.49391565e+00,  1.51589471e-01]])

In [13]:
np.cos(a1) #cos

array([[ 0.54030231, -0.9899925 ,  0.28366219,  0.75390225, -0.91113026],
       [ 0.0044257 ,  0.90744678, -0.75968791, -0.27516334,  0.98870462]])

In [14]:
np.greater(a2,a1) #greater

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [19]:
# Create a random array
r1 = np.random.randint(1,20,10).reshape(2,5)
r1

array([[ 7, 15,  5, 19,  8],
       [16,  5, 11,  2,  1]])

In [20]:
np.greater(r1,a1)

array([[ True,  True, False,  True, False],
       [ True, False, False, False, False]])

In [21]:
r1 < a1 

array([[False, False, False, False,  True],
       [False,  True,  True,  True,  True]])

In [22]:
r1 > a1

array([[ True,  True, False,  True, False],
       [ True, False, False, False, False]])

In [23]:
r1 > 10 # how many elements are greater than 10

array([[False,  True, False,  True, False],
       [ True, False,  True, False, False]])

In [24]:
r1.max() #max

19

In [25]:
r1.min() #min

1

In [28]:
np.maximum(r1,a1) #maximun

array([[ 7, 15,  5, 19,  9],
       [16, 13, 15, 17, 19]])

In [29]:
np.max(r1) # max

19

In [30]:
np.isinf(1/a1) #isinf (zero resulted)

array([[False, False, False, False, False],
       [False, False, False, False, False]])