In [1]:
import numpy as np

In [2]:
np.random.rand()

0.6742584644433688

In [3]:
np.random.rand(10)

array([0.44672638, 0.49746279, 0.66074475, 0.50461775, 0.48315498,
       0.47606017, 0.45531721, 0.28089588, 0.6468266 , 0.16065019])

In [4]:
np.random.randn()

2.8967664342077386

In [5]:
np.random.randn(10)

array([-0.88024772,  1.70518556,  0.2744276 ,  0.9536188 , -2.26621984,
       -1.34768121, -0.00961272, -0.73072058,  1.14560615, -0.00970745])

In [7]:
np.random.randint(1,10)

3

In [8]:
np.random.randint(1,10,10)

array([4, 1, 8, 9, 2, 7, 7, 1, 5, 7])

In [11]:
ar = np.random.randint(1,100, 25)
ar

array([61, 50, 48, 78, 17, 38, 81, 26, 60, 40, 29, 34, 54, 92, 74, 90, 44,
       39, 49, 58, 45, 12, 51, 24, 39])

In [13]:
ar.shape

(25,)