In [1]:
import numpy as np

In [3]:
#create an array
ar2d = np.arange(12).reshape(4,3) #4rows | 3 columns
ar2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
ar2d[0] #row 0

array([0, 1, 2])

In [6]:
ar2d[1] #row 1 #TIP: One ROW from 2d Array is 1D Array

array([3, 4, 5])

In [7]:
ar2d[2] #row 2

array([6, 7, 8])

In [9]:
ar2d[3] #row 3

array([ 9, 10, 11])

#### The array

In [11]:
#create an array
ar2d = np.arange(12).reshape(4,3) #4rows | 3 columns
ar2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### by Row

In [28]:
ar2d[0][:]

array([0, 1, 2])

In [29]:
ar2d[1][:]

array([3, 4, 5])

In [32]:
ar2d[1,:] #another option same result |  concept

array([3, 4, 5])

In [30]:
ar2d[2][:]

array([6, 7, 8])

In [31]:
ar2d[3][:]

array([ 9, 10, 11])

#### Slicing by rows and columns

In [10]:
ar2d[1][1] # 1 row | 1 element of the row 1

4

In [12]:
#select the element 11
ar2d[3][2]

11

In [13]:
#select the element 10
ar2d[3][1]

10

In [14]:
#select the element 9
ar2d[3][0]

9

In [15]:
#select the element 8
ar2d[2][2]

8

In [24]:
ar2d[2,2]

8

In [16]:
#select the element 7
ar2d[2][1]

7

In [26]:
ar2d[2,1]

7

In [17]:
#select the element 6
ar2d[2][0]

6

In [18]:
#select the element 5
ar2d[1][2]

5

In [19]:
#select the element 4
ar2d[1][1]

4

In [25]:
ar2d[1,1]

4

In [20]:
#select the element 3
ar2d[1][0]

3

In [21]:
#select the element 2
ar2d[0][2]

2

In [22]:
#select the element 1
ar2d[0][1]

1

In [23]:
#select the element 0
ar2d[0][0]

0

#### the array

In [33]:
ar2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
#select row 0 and 1
ar2d[0:2,]

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
#select the 3rd column
ar2d[0:2,1]

array([1, 4])

In [40]:
ar2d[:2,1]

array([1, 4])

In [39]:
#select the 4th column
ar2d[0:2,2]

array([2, 5])

In [41]:
ar2d[:2,2]

array([2, 5])

In [35]:
#select the last two columns
ar2d[0:2,1:3]

array([[1, 2],
       [4, 5]])

In [42]:
ar2d[:2,1:3]

array([[1, 2],
       [4, 5]])

In [43]:
# create an array 
ar = np.arange(10,20)
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [44]:
# how many elements are greater then 15?
np.greater(ar,15) #need the array, condition=15

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [45]:
ar > 15

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [46]:
ar2 = ar > 15
ar2

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [47]:
ar[ar2]

array([16, 17, 18, 19])

In [48]:
ar[ar > 15]

array([16, 17, 18, 19])