In [1]:
import numpy as np

In [2]:
ar = np.arange(10,20) #array start number 10 to 20
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

#### Indexing 

In [24]:
ar[0:10]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [3]:
ar[0:9]

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [4]:
ar[0:8]

array([10, 11, 12, 13, 14, 15, 16, 17])

In [5]:
ar[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [6]:
ar[0:6]

array([10, 11, 12, 13, 14, 15])

In [7]:
ar[0:5]

array([10, 11, 12, 13, 14])

In [8]:
ar[0:4]

array([10, 11, 12, 13])

In [9]:
ar[0:3]

array([10, 11, 12])

In [10]:
ar[0:2]

array([10, 11])

In [11]:
ar[0:1]

array([10])

In [13]:
ar[0]

10

In [14]:
ar[0:1]

array([10])

In [15]:
ar[0:2]

array([10, 11])

In [16]:
ar[0:3]

array([10, 11, 12])

In [17]:
ar[0:4]

array([10, 11, 12, 13])

In [18]:
ar[0:5]

array([10, 11, 12, 13, 14])

In [19]:
ar[0:6]

array([10, 11, 12, 13, 14, 15])

In [20]:
ar[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [21]:
ar[0:8]

array([10, 11, 12, 13, 14, 15, 16, 17])

In [22]:
ar[0:9]

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [23]:
ar[0:10]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
ar[0]

10

In [26]:
ar[1]

11

In [27]:
ar[2]

12

In [28]:
ar[3]

13

In [29]:
ar[4]

14

In [30]:
ar[5]

15

In [31]:
ar[6]

16

In [32]:
ar[7]

17

In [33]:
ar[8]

18

In [34]:
ar[9]

19

In [36]:
ar[:] # all elements

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

#### Changing or adding values

In [37]:
ar[:3]

array([10, 11, 12])

In [38]:
ar[:3] = [20,30,40]

In [39]:
ar[:3]

array([20, 30, 40])

In [40]:
ar[:]

array([20, 30, 40, 13, 14, 15, 16, 17, 18, 19])

#### COMMON MISTAKE #1 : Broadcasting

In [41]:
# supose to set all the element as Hundreds
ar = np.arange(10,20)
ar[:] = 100
ar

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [43]:
ar = np.arange(10,20)
ar2 = ar[:3]
ar2

array([10, 11, 12])

In [44]:
ar2[0] = 99 #prblem = check the original ar if also changed
ar2

array([99, 11, 12])

In [45]:
ar # changed

array([99, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [46]:
# first we reset the original aray and make the copy
ar = np.arange(10,20) #10 to 19
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
# create the proper copy of the first 3 elements of the original array
ar2 = ar[:3].copy()
ar2

array([10, 11, 12])

In [48]:
ar2[0] = 99 #change the first value 10 to 99
ar2

array([99, 11, 12])

In [49]:
#check the original array if also changed or not
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])