In [1]:
import numpy as np


In [2]:
l = [[1,2,3], [1,3,5],[6,8,9]]
l

[[1, 2, 3], [1, 3, 5], [6, 8, 9]]

In [6]:
ar = np.array(l)

In [7]:
ar

array([[1, 2, 3],
       [1, 3, 5],
       [6, 8, 9]])

In [8]:
ar.shape

(3, 3)

In [11]:
np.shape(ar)

(3, 3)

In [9]:
np.zeros((3, 3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [12]:
ar = np.ones((3,6))
ar

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
ar.reshape(6,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
ar.reshape(9,2) #(9,3) value error

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
ar = np.arange(1,11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
ar.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
ar = np.arange(25).reshape(5,5)

In [19]:
ar.shape

(5, 5)