### Support Vector Machine

### Loading the data

In [1]:
#import the libraries 
import pandas as pd
import numpy as np 

In [2]:
#import load wine
from sklearn.datasets import load_wine

In [3]:
#store it into a variable 
wine = load_wine()

In [4]:
#a Dcitionary key
wine.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [7]:
#look at the DESCR column
print(wine.DESCR)
#13 numeric attributes
#3 classes

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            10.6  30.0    19.5   3.3
    Ma

In [11]:
wine.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [12]:
# look at the column name = feature_names
wine["feature_names"]

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [13]:
#an array
wine.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

##### ...start with creating a pandas data frame 


In [14]:
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df.head()
# but we dont have the target

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [20]:
# create one more data frame as df_target
df_target = pd.DataFrame(wine.target,columns=['WineType'])
df_target['WineType'].unique()

array([0, 1, 2])

In [21]:
df_target.head()

WineType
0         0
1         0
2         0
3         0
4         0

### Scaling 

In [22]:
#df_describe = frist df
df.describe()
#look at the mean = the date are not scale, on the same scale

alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       color_intensity         hue  od280/od315_of_diluted_wines      proline  
count       178.000000  178.000000                    178.000000   178.000000  
mean          5.058090    0.957449                      2.611685   746.893258  
std           2.318286    0.228572                      0.709990   314.907474  
min           1.280000    0.480000                      1.270000   278.000000  
25%           3.220000    0.782500                      1.937500   500.500000  
50%           4.690000    0.965000                      2.780000   673.500000  
75%           6.200000    1.120000                      3.170000   985.000000  
max          13.000000    1.710000                      4.000000  1680.000000

In [23]:
#call the StandardScaler
from sklearn.preprocessing import StandardScaler

In [24]:
#create an object and the instance 
ss = StandardScaler()

In [26]:
#fit_transform
arr = ss.fit_transform(df)
#data transformed into a NP Array

In [27]:
#### ...re create the first DF 
dfs = pd.DataFrame(arr, columns=wine.feature_names)

In [28]:
dfs.head()

alcohol  malic_acid       ash  alcalinity_of_ash  magnesium  \
0  1.518613   -0.562250  0.232053          -1.169593   1.913905   
1  0.246290   -0.499413 -0.827996          -2.490847   0.018145   
2  0.196879    0.021231  1.109334          -0.268738   0.088358   
3  1.691550   -0.346811  0.487926          -0.809251   0.930918   
4  0.295700    0.227694  1.840403           0.451946   1.281985   

   total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
0       0.808997    1.034819             -0.659563         1.224884   
1       0.568648    0.733629             -0.820719        -0.544721   
2       0.808997    1.215533             -0.498407         2.135968   
3       2.491446    1.466525             -0.981875         1.032155   
4       0.808997    0.663351              0.226796         0.401404   

   color_intensity       hue  od280/od315_of_diluted_wines   proline  
0         0.251717  0.362177                      1.847920  1.013009  
1        -0.293321  0.406051                      1.113449  0.965242  
2         0.269020  0.318304                      0.788587  1.395148  
3         1.186068 -0.427544                      1.184071  2.334574  
4        -0.319276  0.362177                      0.449601 -0.037874

### Training and Predicting 

In [29]:
#its time to split the data 
from sklearn.model_selection import train_test_split

In [30]:
#X values 
X = dfs

In [36]:
#y = target
y = df_target['WineType']

##### train_test_split(shift+tab) and paste = X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [34]:
#lets import support_vector_classifier
from sklearn.svm import SVC

In [38]:
#create the instance 
svc = SVC()

In [39]:
#So, lets fit the model
svc.fit(X_train, y_train)

SVC()

#### ...make some predictions

In [40]:
#prediction 1 
y_pred = svc.predict(X_test)

In [41]:
#meassures the effectivenes or the accuracy of the result
from sklearn.metrics import classification_report, confusion_matrix

In [42]:
#confusion matrix 
print(confusion_matrix(y_test, y_pred))
#notice the diagonal the values look good

[[20  0  0]
 [ 0 24  0]
 [ 0  1 14]]


In [44]:
#classification_report 
print(classification_report(y_test, y_pred))
#98% accuracy is extremely good

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       0.96      1.00      0.98        24
           2       1.00      0.93      0.97        15

    accuracy                           0.98        59
   macro avg       0.99      0.98      0.98        59
weighted avg       0.98      0.98      0.98        59



#### lets see without scaling what happens

In [45]:
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.33, random_state=42)  #df

In [46]:
#So, lets fit the model
svc.fit(X_train, y_train)
#prediction 2 
y_pred2 = svc.predict(X_test)

In [47]:
#confusion matrix 
print(confusion_matrix(y_test, y_pred2))
#classification_report 
print(classification_report(y_test, y_pred2))
#notice 71% accuracy

[[20  0  0]
 [ 0 15  9]
 [ 0  8  7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       0.65      0.62      0.64        24
           2       0.44      0.47      0.45        15

    accuracy                           0.71        59
   macro avg       0.70      0.70      0.70        59
weighted avg       0.72      0.71      0.71        59

