In [3]:
import numpy as np

**Lets create two 1D array**

In [4]:
A = np.array([[1,2,1], [2,2,3]])
B = np.array([3,4,5])

In [5]:
A

array([[1, 2, 1],
       [2, 2, 3]])

In [6]:
B

array([3, 4, 5])

**Adding both array togehter** Add Method

In [8]:
np.add(A,B)

array([[4, 6, 6],
       [5, 6, 8]])

**Substract Method** to subtract a numpy array

In [9]:
np.subtract(B,A)

array([[2, 2, 4],
       [1, 2, 2]])

**Multiply Method**

In [10]:
np.multiply(A,B)

array([[ 3,  8,  5],
       [ 6,  8, 15]])

**Divide Method**

In [11]:
np.divide(A,B)

array([[0.33333333, 0.5       , 0.2       ],
       [0.66666667, 0.5       , 0.6       ]])

**Power Method**

In [13]:
np.power(A,2)

array([[1, 4, 1],
       [4, 4, 9]], dtype=int32)

In [14]:
np.power(A,B)

array([[  1,  16,   1],
       [  8,  16, 243]], dtype=int32)