In [1]:
 import numpy as np

In [19]:
array_1d = np.array([1,2,3,4,5,6])
array_2d = np.array([[1,2,3],[4,5,6]])
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [3]:
array_1d.ndim

1

In [4]:
array_2d.ndim

2

In [5]:
array_3d.ndim

3

**slicing array_1d**

In [6]:
array_1d[0]

1

In [7]:
array_1d[1]

2

In [8]:
array_1d[2]

3

In [9]:
array_1d[3]

4

In [10]:
array_1d[4]

5

In [12]:
array_1d[-3]

4

In [23]:
array_1d[1:] #index 2  

array([2, 3, 4, 5, 6])

In [24]:
array_1d[3:5] #slicing from3-5 index

array([4, 5])

In [26]:
array_1d[-3:-1] #slicing from 4 to the last element

array([4, 5])

**slicing array_2d**

In [13]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
array_2d[0,0] #First element

1

In [15]:
array_2d[0,1] #First element of the second row

2

In [17]:
array_2d[1,-1] #return the last element

6

In [29]:
array_2d[1,1:] #last two indexes 

array([5, 6])

In [30]:
array_2d[-2:-3:-1]

array([[1, 2, 3]])

**slicing array_3d**

In [20]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [21]:
array_3d[0,1,2] #third element in the second row of the first element

6

In [22]:
array_3d[1,1,-1] #last element

12

In [33]:
array_3d[0,1:,1:] #we slice the first row, then select first element of the second row and six

array([[5, 6]])