# Numpy Array Shapes and axes 

In [1]:
import numpy as np

In [2]:
np.array(24)

array(24)

**Lets create 1D array**

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

**Lets create 2D array**

In [5]:
np.array([[1,1,1], [1,2,1]])

array([[1, 1, 1],
       [1, 2, 1]])

**Lets create 3D array**

In [8]:
np.array([[[1,1,1], [2,2,2]], [[3,3,3], [4,4,4]]])

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

**Lets create a variable**

In [9]:
numpy_arr = np.array([[[1,1,1], [2,2,2]], [[3,3,3], [4,4,4]]]) # 3d

In [10]:
numpy_arr.shape

(2, 2, 3)

In [13]:
numpy_arr_1D = np.array([1,2,3,4]) # 1d

In [14]:
numpy_arr_1D.shape

(4,)

In [16]:
numpy_arr_2D = np.array([[1,1,1], [1,2,1]]) #2D

In [17]:
numpy_arr_2D.shape

(2, 3)

**Number of dimension**

In [11]:
numpy_arr.ndim #3D

3

In [15]:
numpy_arr_1D.ndim #1D

1

In [19]:
numpy_arr_2D.ndim #2D

2

**Lets create another way a 1D array and transformt it into a 3D array**

In [20]:
numpy_arr_new = np.array([x for x in range(1,10)])

In [21]:
numpy_arr_new

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
numpy_arr_new.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Another Sample, lets create another way a 1D array and transformt it into a 3D array**

In [24]:
numpy_arr_new3 = np.array([x for x in range(1,13)])

In [25]:
numpy_arr_new3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
numpy_arr_new3.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
numpy_arr_new3.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

**Reshape method is useful when using dynamics data sets**

In [28]:
numpy_arr_new3.reshape(2,2,-1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

**Lets create the variable**

In [29]:
numpy_arr_new3 = numpy_arr_new3.reshape(3,2,2)

In [30]:
numpy_arr_new3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [31]:
numpy_arr_new3.reshape(-1) #1D Numpy Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])