### Deep_Learning_Frameworks

* Keras is the highl level API in TensorFlow 2.0
* PyTorch
* Theano
* DL4J
* Chainer
*  Caffe

** TensorFlow ** is a popular open-source library released in 2015 by Google Brain team for building machine learning and deep learning models.

** Tensorflow ** works efficiently with multi-dimensional arrays | Supports fast debugging and model building | Provides scalability of computation across machines and large data sets | Has a large community and provides TensorBoard to visualize the model.

** Tensorflow ** tensors are defined by a unit of dimensionality called as rank | Entity (Scalar, Vector, Matrix, Tensor) | Rank (0,1,2,3).

** Tensorflow ** performs computations with the help of dataflow graphs. It has nodes that represent the operations in your model | Compute the below function = a(b = 4,c = 3,d = 6) = (b+c) * (d-4) | x = (4+3) | y = (6-4) |  a = 7*2=14.

** Tensorflow ** varibles are in-memory buffers that store tensors.

** Tensorflow ** a session in TensorFlow is used to run a computational graph to evaluate the nodes.

** Tensorflow ** it required VE up --version 2.0.

** https://www.tensorflow.org/api_docs/python/tf/math

### Demo using TensorFlow 2.0

In [7]:
import tensorflow as tf
print(('Your TensorFlow version is {0}').format(tf.__version__))

Your TensorFlow version is 2.4.0


##### Create a constant tensor A

In [10]:
A = tf.constant([[4, 3],
                 [6, 11]])
A 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  3],
       [ 6, 11]])>

##### Create a constant tensor V

In [14]:
V = tf.Variable([[3, 1],
                 [5, 2]])
# Create another tensor B
B = tf.constant([[7, 8],
                 [4, 5]])
print(V)
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 1],
       [5, 2]])>


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [4, 5]])>

#### Concatenated columns shape ~ (2,2,2)

In [15]:
AB_concatenated = tf.concat(values=[A, B], axis=1)
AB_concatenated #Numpy Array als format to visualize / show

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 4,  3,  7,  8],
       [ 6, 11,  4,  5]])>

In [16]:
# We can concatenate by rows
AB_concatenated = tf.concat(values=[A, B], axis=0)
AB_concatenated

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 4,  3],
       [ 6, 11],
       [ 7,  8],
       [ 4,  5]])>

In [17]:
tensor = tf.zeros(shape=[3, 4], dtype=tf.float32)
tensor # Work with Nan Values, complicated & not recomended

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [18]:
tensor = tf.ones(shape=[3, 4], dtype=tf.float32)
tensor # best practices

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

#### Just for fun 

In [22]:
tensor = tf.random.uniform(shape=[3, 4], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.2506795 , 0.45040798, 0.6034514 , 0.4196434 ],
       [0.313735  , 0.00455129, 0.9177182 , 0.45943904],
       [0.95105886, 0.12323821, 0.94903374, 0.07389629]], dtype=float32)>

#### Reshape the Tensor

In [21]:
reshaped_tensor = tf.reshape(tensor = tensor, shape = [4,3])
reshaped_tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.8378295 , 0.47556627, 0.0994699 ],
       [0.18797433, 0.49291027, 0.65116143],
       [0.8427844 , 0.11754668, 0.23283875],
       [0.18398273, 0.37679553, 0.5196949 ]], dtype=float32)>

#### Typecast a tensor

In [24]:
tensor = tf.constant([[4.6, 4.2],
                      [7.5, 3.6],
                      [2.7, 9.4],
                      [6.7, 8.3]],
                      dtype=tf.float32)
tensor_as_int = tf.cast(tensor, tf.int32)
print(tensor)
print(tensor_as_int)                  

tf.Tensor(
[[4.6 4.2]
 [7.5 3.6]
 [2.7 9.4]
 [6.7 8.3]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[4 4]
 [7 3]
 [2 9]
 [6 8]], shape=(4, 2), dtype=int32)


#### Transpose like reshape 

In [26]:
a = tf.transpose(tensor_as_int)
tensor_as_int

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 4],
       [7, 3],
       [2, 9],
       [6, 8]])>

### Doing diff Maths function

In [30]:
# Matrix multiplication of tensors
A = tf.constant([[5, 8],
                 [3, 9]])

# Some vector v
v = tf.constant([[4],
                 [2]])

Av = tf.matmul(A, v) #matrix multiplier
Av

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[36],
       [30]])>

In [31]:
# Element-wise multiplication 
Av = tf.multiply(A,v)
Av

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 32],
       [ 6, 18]])>

In [41]:
# Creating an identity matrix 
A = tf.constant([[4, 9],
                 [5, 6],
                 [1, 8]])
rows, columns = A.shape
print('rows:', rows, 'columns:', columns)

# Making an identity matrix 
A_identity = tf.eye(num_rows = rows,
                   num_columns = columns, 
                   dtype = tf.int32)
A_identity

rows: 3 columns: 2


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1],
       [0, 0]])>