# Array Manipulation

#### Array Manipulation - changing shape

In [3]:
import numpy as np

a = np.arange(9) #original array
print('The original array:')
print(a)
print()

b = a.reshape(3,3) #modified array
print("The modified array:")
print(b)

The original array:
[0 1 2 3 4 5 6 7 8]

The modified array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
print(b.flatten()) #flatten

[0 1 2 3 4 5 6 7 8]


In [5]:
b.flatten(order = "F")

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [7]:
a = np.arange(12).reshape(4,3) #reshape / 12 elements
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
np.transpose(a) #transpose

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [10]:
print(np.transpose(a)) #transpose

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [16]:
c = np.arange(8).reshape(2,4)
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
c.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])