# Numpy Arithmetic Operations

In [1]:
import numpy as np

a = np.arange(9) #original array
print('The original array:')
print(a)

The original array:
[0 1 2 3 4 5 6 7 8]


In [3]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
b = np.array([10,10,10]) #second array
b

array([10, 10, 10])

In [10]:
np.add(a,b) #array b + a 

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [12]:
np.subtract(a,b) # array a - b

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [13]:
np.subtract(b,a) #array b -a 

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

In [14]:
np.multiply(a,b) #multiply

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

### Array Slicing 

In [16]:
a = np.arange(20) #array
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
a.ndim #1D array

1

In [20]:
a.size #size

20

In [21]:
a[:4] #all element before the 5th element

array([0, 1, 2, 3])

In [22]:
a[5] #5th element

5

In [23]:
s = slice(2,9,2) # start at 2 / end at 9 = 8 / 2 = steps every 2 element = after 2 = 4, 6
a[s]

array([2, 4, 6, 8])

In [25]:
s = slice(2,12,3) 
a[s]

array([ 2,  5,  8, 11])

### Iterating Over Array

In [28]:
a = np.arange(0,45,5)
a = a.reshape(3,3)
a

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [29]:
for x in np.nditer(a):
    print(x)

0
5
10
15
20
25
30
35
40


### Iteration order (c-style and f-style)

In [30]:
print(a)
for x in np.nditer(a, order="C"):
    print(x)

for x in np.nditer(a, order ="F"):
    print(x)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]
0
5
10
15
20
25
30
35
40
0
15
30
5
20
35
10
25
40


### Joining arrays

In [37]:
a = np.array([[1,2],[3,4]]) #array 1
print('first array')
print(a)

b = np.array([[5,6],[7,8]]) #array 2
print('second array')
print(b)

print( '\n') #both arrays concatenated
print( 'Joining the two arrays along axis 0:') #axis 0
print( np.concatenate((a,b)) )
print( '\n')
print( 'Joining the two array along axis 1:' ) #axis 1
print( np.concatenate((a,b), axis =1))

first array
[[1 2]
 [3 4]]
second array
[[5 6]
 [7 8]]


Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Joining the two array along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [32]:
a.ndim #2d array

2

In [33]:
b.ndim #2d array

2

### Splitting array

In [38]:
a = np.arange(9)
print(a)
np.split(a,3)

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [39]:
np.split(a,[4,5])

[array([0, 1, 2, 3]), array([4]), array([5, 6, 7, 8])]

In [40]:
np.split(a,[4,7])

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

### Resizing an array

In [46]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape )
print('\n')

# resize(3,2)
b = np.resize(a, (3,2))
print(b)
print(b.shape)

#resize (3,3)
b = np.resize(a, (3,3))
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2 3]
 [4 5 6]
 [1 2 3]]
(3, 3)
