In [1]:
import numpy as np

In [3]:
arr = np.array([[4,3,2], [10,1,0], [5,8,24]])
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [4]:
arr.ndim #2D

2

In [6]:
np.amin(arr) #MIN values

0

In [7]:
np.amin(arr,axis=0)

array([4, 1, 0])

In [8]:
np.amin(arr,axis=1)

array([2, 0, 5])

In [10]:
np.max(arr) #MAX values

24

In [11]:
np.amax(arr,axis=0)

array([10,  8, 24])

In [12]:
np.amax(arr,axis=1)

array([ 4, 10, 24])

In [13]:
np.median(arr) #MEDIAN

4.0

In [14]:
np.mean(arr) #MEAN

6.333333333333333

In [15]:
np.std(arr) #STD

6.944222218666553

In [16]:
np.var(arr) #VARIANCE

48.22222222222222

In [17]:
np.percentile(arr,50) #PERCENTILE

4.0

**Lets create a numpy array**

In [18]:
deg = np.array([0,30,45,60,90])

In [19]:
deg

array([ 0, 30, 45, 60, 90])

**Lets convert grad to radius**

In [22]:
np.sin(deg*np.pi/180) #SIN

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [23]:
np.cos(deg*np.pi/180) #COS

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [24]:
np.tan(deg*np.pi/180) #TAN

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])