<h3> Get to Know a Numpy Array </h3>

You will use the numpy array <code>A</code> for the following questions.

In [9]:
import numpy as np

In [11]:
A=np.array([[11,12],[21,22],[31,32]])

1) Find the type of `x` using the function `type()`.

In [12]:
type(A)

numpy.ndarray

2) Find the shape of the array:

In [13]:
A.shape

(3, 2)

3) Find the type of data in the array:

In [14]:
A.dtype

dtype('int32')

4) Find the second row of the numpy array <code>A</code>:

In [22]:
A[1]

array([21, 22])

<h3>Two Types of Multiplication</h3>

You will use the following numpy arrays for the next questions: 

In [19]:
A=np.array([[11,12],[21,22]])
B=np.array([[1, 0],[0,1]])

1) Multiply array <code>A</code> and <code>B</code>.

In [20]:
C = A *B
C

array([[11,  0],
       [ 0, 22]])

2)  Perform matrix multiplication on array <code>A</code> and <code>B</code> (order will not matter in this case).

In [21]:
Z = np.dot(A,B)
Z

array([[11, 12],
       [21, 22]])