<div align="center">
    <h4 style="font-size: 50;">Numpy</h4>
</div>

* Create 1D and 2D arrays, including some special arrays
* Slice, index, reshape, sort an array
* Perform numerical operations on arrays

In [2]:
# import package Numpy
import numpy as np

#### Create 1D array (column vectors)

In [3]:
x = np.array([1,2,10,2,1])

In [4]:
type(x)

numpy.ndarray

In [6]:
x

array([ 1,  2, 10,  2,  1])

In [5]:
# shape of the array, which shall be a 5 x 1 column vector 
x.shape

(5,)

In [7]:
# number of rows
len(x)

5

In [8]:
# first element of the array x
x[0]

1

In [9]:
# second element of the array x
x[1]

2

In [10]:
# last element of the array x
x[-1]

1

In [11]:
# first 2 elements of the array x
x[:2]

array([1, 2])

In [12]:
# last 2 elements of the array x
x[-2:]

array([2, 1])

In [13]:
# from the 2nd to the 4th elements of the array x
x[1:4]

array([ 2, 10,  2])

In [14]:
# dimension of the array x
x.ndim

1

#### Create 2D array (matrices)

In [15]:
y = np.array([[1,2], [3,4]])

In [16]:
y

array([[1, 2],
       [3, 4]])

In [17]:
# you can also use list to create a 2-dmin array
n1 = [1,2,3]
n2 = [4,5,6]
n3 = [7,8,9]
n4 = [10,11,12]
m = np.array([n1, n2, n3, n4])

In [18]:
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
m.ndim

2

In [20]:
m.shape # (# rows, # columns)

(4, 3)

In [21]:
len(m)

4

In [22]:
# the 1st row of matrix m
m[0,:]

array([1, 2, 3])

In [24]:
# the first two rows of matrix m
m[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
# the 1st column of matrix m
m[:,0]

array([ 1,  4,  7, 10])

In [26]:
# the last two column of matrix m
m[:,-2:]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [27]:
# the 4th row and 2nd column element (answer shall be 11)
m[3,1]

11

In [30]:
# the 4th row and 1st column element (answer shall be 10)
m[3,0]

10

In [29]:
# the 4th row and 3rd column element (answer shall be 12)
m[3,2]

12

#### Create special 2-dimnesional arrays (ones, zeros, diag, eye, empty, random)

In [31]:
# diag matrix
np.diag((5,5,1,1))

array([[5, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [33]:
# matrix with all entries equal to 1
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
# zero matrix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [35]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# array of normally distributed values
np.random.normal(size=4)

array([-1.96341785, -0.6467253 ,  1.02329083, -0.41674857])

In [38]:
# array of normally distributed values 
np.random.normal(size=(4,4))

array([[ 2.16867289, -0.24827687,  0.11648011,  0.08502524],
       [ 0.42549435, -0.07146949,  1.49092271,  1.47348722],
       [-2.55321542,  0.37334617, -0.31050236, -0.56342392],
       [-0.61152675, -1.28911108, -0.81101183,  0.29803937]])

#### Data Types

In [39]:
x = np.array([1,2,3])
x.dtype

dtype('int32')

In [40]:
x

array([1, 2, 3])

In [41]:
x = np.array([1,2,3], dtype=float)
x.dtype

dtype('float64')

In [42]:
x = np.array([1,2,3])
x = x.astype(float)
x

array([1., 2., 3.])

In [44]:
# If you mix types, the most complex type is used
np.array([1.0, 1, "oups"])

array(['1.0', '1', 'oups'], dtype='<U32')

#### Indexing with boolean masks

In [45]:
x = np.array([-10,-5,-0.1,0,2,5,6,10000])

In [46]:
# check each element in array x whether its less than 0 or not
x<0

array([ True,  True,  True, False, False, False, False, False])

In [47]:
# pick all elements which are less than 0 in array x
x[x<0]

array([-10. ,  -5. ,  -0.1])

In [49]:
# check each element in array x whether its even or not
x % 2 == 0

array([ True, False, False,  True,  True, False,  True,  True])

In [50]:
# pick all even elements in array x
x[x % 2 == 0]

array([-1.e+01,  0.e+00,  2.e+00,  6.e+00,  1.e+04])

In [51]:
# convert all even elements to integers
x[x % 2 == 0].astype(int)

array([  -10,     0,     2,     6, 10000])

#### Numerical operations

In [53]:
A = np.array([[4,7],
             [2,6]])

B = np.array([[0.6,-0.7],
             [-0.2,0.4]])

In [54]:
A + B

array([[4.6, 6.3],
       [1.8, 6.4]])

In [55]:
A - B

array([[3.4, 7.7],
       [2.2, 5.6]])

In [56]:
# elementwise product
A * B

array([[ 2.4, -4.9],
       [-0.4,  2.4]])

In [57]:
# matrix product
A.dot(B)

array([[ 1.00000000e+00,  3.33066907e-16],
       [-1.11022302e-16,  1.00000000e+00]])

In [58]:
A.dot(B).round()

array([[ 1.,  0.],
       [-0.,  1.]])

In [59]:
# elementwise division
A/B

array([[  6.66666667, -10.        ],
       [-10.        ,  15.        ]])

#### reshape

In [60]:
a = np.array([[1,2,3],[4,5,6]])

In [61]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
a.shape

(2, 3)

In [63]:
# reshape to a 3x2 array
b = a.reshape(3,2)

In [64]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
b.shape

(3, 2)

In [66]:
# reshape to a 1x6 array
c = a.reshape((1,6))

In [67]:
c

array([[1, 2, 3, 4, 5, 6]])

In [68]:
c.shape

(1, 6)

#### sorting

In [70]:
X = np.array([5,1,10,2,7,8])
x.sort() # inplace
X

array([ 5,  1, 10,  2,  7,  8])

In [73]:
X = np.array([5,1,10,2,8])
np.sort(X)

array([ 1,  2,  5,  8, 10])

##### Summary

1. How to create arrays with : array, ones, diag, zeros, ....
2. How to check array's shape and dimensions
3. Perform slicing and indexing arrays
4. How to use operators. Keep in mind that * operator is an element-wise operation
5. How to reshape and sort an array
6. Reference: http:/numpy.org