In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel("E:\DATA SETS\Iris_mini.xlsx", index_col=0)
df

SL  SW  PL  PW          Species
Id                                 
A   51  35  14   2      Iris-setosa
B   49  30  14   2      Iris-setosa
C   70  32  47  14  Iris-versicolor
D   64  32  45  15  Iris-versicolor
E   63  33  60  25   Iris-virginica
F   58  27  51  19   Iris-virginica

In [4]:
# drop the species column
df.drop('Species',axis=1,inplace=True)
df

SL  SW  PL  PW
Id                
A   51  35  14   2
B   49  30  14   2
C   70  32  47  14
D   64  32  45  15
E   63  33  60  25
F   58  27  51  19

In [5]:
#create an  numpy array
ar = np.arange(5)
ar

array([0, 1, 2, 3, 4])

In [6]:
# braodcasting +10
ar + 10

array([10, 11, 12, 13, 14])

In [7]:
#check condition < 3
ar < 3 

array([ True,  True,  True, False, False])

In [8]:
df

SL  SW  PL  PW
Id                
A   51  35  14   2
B   49  30  14   2
C   70  32  47  14
D   64  32  45  15
E   63  33  60  25
F   58  27  51  19

In [9]:
df < 6 

SL     SW     PL     PW
Id                            
A   False  False  False   True
B   False  False  False   True
C   False  False  False  False
D   False  False  False  False
E   False  False  False  False
F   False  False  False  False

In [16]:
# check condition on SL column if the elements are < 6
filter = df['SL'] > 6
filter

Id
A    True
B    True
C    True
D    True
E    True
F    True
Name: SL, dtype: bool

In [15]:
df2 = df[df['SL'] > 6]
df2

SL  SW  PL  PW
Id                
A   51  35  14   2
B   49  30  14   2
C   70  32  47  14
D   64  32  45  15
E   63  33  60  25
F   58  27  51  19

In [ ]:
#another way

In [17]:
#check the condition
filter = df['SL'] > 6
# store it 
df3 = df[filter]
#select PL column
df3['PL']

Id
A    14
B    14
C    47
D    45
E    60
F    51
Name: PL, dtype: int64

In [ ]:
#selecting more than one condition
df[df]