<center><h1><b><font size="6">Pandas Series: Converting Series into Arrays</font></b></h1></center>

#### Pandas Series: .values, .array, .to_numpy()

#### Import libraries

In [1]:
import pandas as pd
import numpy as np

#### Series

In [2]:
prices_per_category = pd.Series({'Product A': 22250, 'Product B': 16600, 'Product C': 15600})
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

#### .values

In [3]:
prices_per_category.values

array([22250, 16600, 15600], dtype=int64)

In [4]:
type(prices_per_category.values)

numpy.ndarray

#### .array

In [5]:
prices_per_category.array

<PandasArray>
[22250, 16600, 15600]
Length: 3, dtype: int64

In [6]:
type(prices_per_category.array)

pandas.core.arrays.numpy_.PandasArray

#### .to_numpy

In [7]:
prices_per_category.to_numpy()

array([22250, 16600, 15600], dtype=int64)

In [8]:
type(prices_per_category.to_numpy())

numpy.ndarray

#### .array

In [9]:
test_array = prices_per_category[['Product A', 'Product B']].to_numpy(dtype='float')
test_array

array([22250., 16600.])

In [10]:
type(test_array[0])

numpy.float64

In [11]:
prices_per_category.values[0]

22250

In [12]:
type(prices_per_category.values[0])

numpy.int64

In [13]:
prices_per_category.array[0]

22250

In [14]:
type(prices_per_category.array[0])

numpy.int64